//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClipMoneyGrupo3C.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cuenta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public cuenta()
        {
            this.inversions = new HashSet<inversion>();
            this.movimientoes = new HashSet<movimiento>();
        }
    
        public int nroCuenta { get; set; }
        public Nullable<int> usuarioId { get; set; }
        public Nullable<int> cvu { get; set; }
        public string alias { get; set; }
        public Nullable<int> tipoMoneda { get; set; }
        public Nullable<decimal> saldo { get; set; }
    
        public virtual tipoMoneda tipoMoneda1 { get; set; }
        public virtual usuario usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<inversion> inversions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<movimiento> movimientoes { get; set; }
    }
}
