//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClipMoneyGrupo3C.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class datosUsuario
    {
        public int usuarioId { get; set; }
        public Nullable<int> telefono { get; set; }
        public Nullable<int> celular { get; set; }
        public string domicilio { get; set; }
        public string localidad { get; set; }
        public string provincia { get; set; }
        public string pais { get; set; }
        public Nullable<short> cp { get; set; }
    
        public virtual usuario usuario { get; set; }
    }
}
