//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClipMoneyGrupo3C.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class inversion
    {
        public int id { get; set; }
        public Nullable<int> cuentaId { get; set; }
        public Nullable<int> usuarioId { get; set; }
        public Nullable<int> movimientoId { get; set; }
        public string nombre { get; set; }
        public Nullable<int> tipoMoneda { get; set; }
        public Nullable<double> taza { get; set; }
        public Nullable<System.DateTime> fechaInicio { get; set; }
        public Nullable<System.DateTime> fechaFin { get; set; }
        public Nullable<bool> renovacion { get; set; }
    
        public virtual cuenta cuenta { get; set; }
        public virtual movimiento movimiento { get; set; }
        public virtual tipoMoneda tipoMoneda1 { get; set; }
        public virtual usuario usuario { get; set; }
    }
}
