//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClipMoneyGrupo3C.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class movimiento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public movimiento()
        {
            this.inversions = new HashSet<inversion>();
            this.pagoServicios = new HashSet<pagoServicio>();
        }
    
        public int id { get; set; }
        public Nullable<int> cuentaId { get; set; }
        public Nullable<int> tipoMovimiento { get; set; }
        public Nullable<decimal> monto { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<bool> estado { get; set; }
    
        public virtual cuenta cuenta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<inversion> inversions { get; set; }
        public virtual tipoMovimiento tipoMovimiento1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pagoServicio> pagoServicios { get; set; }
    }
}
