//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClipMoneyGrupo3C.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pagoServicio
    {
        public int id { get; set; }
        public Nullable<int> servicioId { get; set; }
        public Nullable<int> movimientoId { get; set; }
    
        public virtual movimiento movimiento { get; set; }
        public virtual servicio servicio { get; set; }
    }
}
