//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClipMoneyGrupo3C.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class password
    {
        public int id { get; set; }
        public Nullable<int> usuarioId { get; set; }
        public string valor { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
    
        public virtual usuario usuario { get; set; }
    }
}
